"""Add delivery

Revision ID: 77204d29dd07
Revises: 
Create Date: 2023-11-24 07:06:19.470918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77204d29dd07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ACTIVATED', 'DONE', 'CANCELED', name='deliverystatuses'), nullable=False),
    sa.Column('deliveryman_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deliveries')
    # ### end Alembic commands ###
